### PR TITLE
Fix broken routing

### PR DESCRIPTION
**Pull request by DrewML**
```js
new URL('foo', 'https://site.com/bar').toString() // "https://site.com/foo"

new URL('foo', 'https://site.com/bar/').toString() // "https://site.com/bar/foo"
```

### CODE REVIEW

**Comment by jimbo** [comment]
Simple enough. How should we test it?

**Comment by DrewML** [comment]
> Simple enough. How should we test it?

Good question. Ideally this would be covered by e2e tests with MFTF, but we're not set up for that quite yet from an infrastructure side of things.

I don't actually think we need a test for this specific functionality, though. The bug exists solely in temporary Peregrine logic to fetch the `roots-manifest.json`. This is only a hack that is in place until someone contributes the Root Component query for the GraphQL API.

Thoughts?

**Comment by shakyShane** [comment]
This caught me out just now, since the manual request for the webpack-served roots-manifest.json gives a 404.

**Comment by DrewML** [comment]
@jimbo going to merge this to get new contributors struggling with this unblocked. Will open a PR to `peregrine` to add an early assertion to validate a proper path is being passed in.

**Pull request merged**
